Add collision and distance between ConvexBase and Halfspace.
humanoid-path-planner/hpp-fcl pull request #191
Opened 2020-09-17 09:48 UTC by jmirabel

Partially solves #189 

I haven't tested this. @duburcqa, you may be able to test it quickly in your setup.

2020-09-17 11:33 UTC, jcarpent commented on src/narrowphase/details.h
> +      p1 = p2 - dist * n_2;
Maybe a noalias here can be used.

2020-09-17 11:34 UTC, jcarpent commented on src/distance/triangle_halfspace.cpp
> + *  Copyright (c) 2011-2014, Willow Garage, Inc.
About licensing here, I do think only the copyright of CNRS should appear here because this is new content.

2020-09-17 11:35 UTC, jmirabel commented on src/narrowphase/details.h
> +      p1 = p2 - dist * n_2;
There is no possible aliasing as dist is a scalar.

2020-09-17 11:35 UTC, jcarpent approved these changes
I made just minor remarks.

2020-09-17 11:36 UTC, jcarpent commented on src/narrowphase/details.h
> +      p1 = p2 - dist * n_2;
Yes, the you can directly use noalias to avoid intermediate allocation (even on the stack).

2020-09-17 11:41 UTC, jmirabel commented on src/distance/triangle_halfspace.cpp
> + *  Copyright (c) 2011-2014, Willow Garage, Inc.
Done.

2020-09-17 11:42 UTC, duburcqa commented
Nice thank you ! I'm going to test it asap ! Hopefully tomorrow

2020-09-17 11:44 UTC, jcarpent requested changes

2020-09-17 11:44 UTC, jcarpent commented on python/collision.cc
> +          make_function(&geto<1>, return_internal_reference<>()), &seto<1>,
I don't think this would work well. Because, o1 and o2 might be null and there are not managed by Collision

2020-09-17 12:01 UTC, jmirabel commented on python/collision.cc
> +          make_function(&geto<1>, return_internal_reference<>()), &seto<1>,
I updated the code following our private discussion. Is this correct now ?

2020-09-17 12:32 UTC, jmirabel commented
> Nice thank you ! I'm going to test it asap ! Hopefully tomorrow

If you can make a decent self-contained Python example, that would be wonderful.

2020-09-17 16:26 UTC, jcarpent commented on python/collision.cc
> +          make_function(&geto<1>, return_internal_reference<>()), &seto<1>,
You are still missing the check whether the pointer is empty ;)

2020-09-18 06:41 UTC, jmirabel commented on python/collision.cc
> +          make_function(&geto<1>, return_internal_reference<>()), &seto<1>,
I tried the above code and I get a None when the pointer is NULL. Do I really have to handle it manually ?

2020-09-18 08:52 UTC, jcarpent commented on python/collision.cc
> +          make_function(&geto<1>, return_internal_reference<>()), &seto<1>,
I will try on my side but seems to be fine. After merging this PR, I will make a new release. It would also be nice to add testing over the Python bindings to avoid future bugs.

2020-09-18 08:57 UTC, jmirabel commented on python/collision.cc
> +          make_function(&geto<1>, return_internal_reference<>()), &seto<1>,
> It would also be nice to add testing over the Python bindings to avoid future bugs.

Yes, that would be nice. We also need to unit-test what I added in this PR. I will wait for @duburcqa feedback.

2020-09-18 10:04 UTC, jcarpent commented on python/collision.cc
> +          make_function(&geto<1>, return_internal_reference<>()), &seto<1>,
Sounds good to me.

2020-09-18 10:05 UTC, jcarpent approved these changes

2020-09-19 07:02 UTC, jcarpent commented
@duburcqa We need your test in order to merge and provide an new release. When could you provite it?

2020-09-21 16:49 UTC, jmirabel commented
There is now a very minimalist unit test.

2020-09-21 17:15 UTC, duburcqa commented
Are you sure you added it ? Mine would be minimalist too because it is pretty difficult for me to make a unit test out of the whole programm requiring this type of collision.

2020-09-22 07:02 UTC, jmirabel commented
Indeed, I forgot a file.

2020-09-22 07:59 UTC, jcarpent commented
I will merge it now and provide a new release then

2020-09-22 07:59 UTC, merged