Fix potential bug when returning depth distance when computing collision
humanoid-path-planner/hpp-fcl pull request #198
Opened 2020-10-23 12:34 UTC by jcarpent

2020-10-23 13:46 UTC, florent-lamiraux reviewed
Have tested or encountered issues with this part of the code ?

2020-10-23 13:46 UTC, florent-lamiraux commented on src/collision_func_matrix.cpp
> +  if (distance <= 0 || distance <= request.security_margin) {
I would remove the test `distance <= 0`

2020-10-23 13:46 UTC, florent-lamiraux commented on src/collision_func_matrix.cpp
> +      const Vec3f& normal = distance <= 0 ? distanceResult.normal : (p2-p1).normalized();
if `distance <= 0`, `p1` is likely to be equal to `p2`.

2020-10-23 13:46 UTC, florent-lamiraux commented on src/collision_func_matrix.cpp
> +                       -distance);
I think the penetration should take into account the security margin. Volumes should be thought of as if they were inflated by half the security margin. In any case, It must be consistent with other parts of the code.

2020-10-23 14:41 UTC, jcarpent commented on src/collision_func_matrix.cpp
> +  if (distance <= 0 || distance <= request.security_margin) {
I don't know if I would remove it because users may provide positive security_margin. No?

2020-10-23 14:42 UTC, jcarpent commented on src/collision_func_matrix.cpp
> +      const Vec3f& normal = distance <= 0 ? distanceResult.normal : (p2-p1).normalized();
Not really, because it means you have interpenetration.

2020-10-23 14:47 UTC, jcarpent commented
> Have you tested these modifiations ? Have you encountered issues with this part of the code ?

I've discussed this PR with @jmirabel on personal messages. The thing is that, at the current stage, if:
- two objects interpenetrate, then the returned depth_penetration is positive, and is equal to `-distance + security_margin`
- the distance between the objects is greater than the security_margin, then there is no collision (as expected).
- if the two objects are not in collision, but their distance is lower than security_margin, then the two objects are considred in collision and the depth_penetration is equal to `-distance + security_margin`, meaning that depth_penetration remains positive.

I would rather imagine that the depth_penetration should be a signed value:
- positive, when two objects have a common intersection, with value equal to 0 when the objects are just contacting.
- negative, when the two objects do not intersect, but are at a distance <= security_margin
And there is no collision considered otherwise.

2020-10-23 14:48 UTC, jcarpent commented on src/collision_func_matrix.cpp
> +                       -distance);
I do not agree on this aspect. The `penetration_depth` should be a signed value. In the current context, this is not the case. This PR is trying to fix it.

2020-10-23 14:58 UTC, florent-lamiraux commented
I have no preference on the definition of the penetration depth. It should be consistent for all pairs of shapes. This implies to modify all the specific computations and there are many of them. I have pushed a test on branch "devel" of git@github.com:florent-lamiraux/hpp-fcl.git that confirms the current behavior as expressed above for 2 spheres.

2020-10-23 15:29 UTC, jcarpent commented
I do not see other places where the code should be adjusted if we agree on this convention. Could you provide me some pointers?

2020-10-24 16:12 UTC, jmirabel requested changes
The definition we should stick to are:
![image](https://user-images.githubusercontent.com/2388209/97086055-58886e00-1621-11eb-91d0-439edd33b81d.png)

With a security margin, what is currently implemented is
![image](https://user-images.githubusercontent.com/2388209/97086261-70acbd00-1622-11eb-92f2-9d5158ac8bfa.png)

Function `collision` adds a `Contact` object when `signed_distance_margin(A,B) <= 0`. Class `Contact` has a field for storing the penetration depth (thus unsigned) and this make sense because there is no contact if the signed distance is positive.

@jcarpent, re-reading our discussion, why don't you should use function `distance` rather than `collision` ? I think you would have what you want.

Before we continue on the code, we should agree on the API, if the current one does not fulfill the needs.

Then, if we modify the API, as @florent-lamiraux suggested, there are other places to update (e.g. the BVH <-> something collision functions).

2020-10-26 08:09 UTC, jmirabel commented
After double thinking about it, I think what @jcarpent requests (tell me if I am wrong) is not implemented but the request make sense and shouldn't be hard to implement.

@jcarpent wants (again tell me if I am wrong):
- the contact information as they are now provided when the objects are in contact,
- the closest points when `0 <= signed_distance_margin(A,B) <= threshold`.

The security margin is not the correct way of handling this. I think the correct way of handling this is the request attribute `break_distance`. At the moment, when `0 <= signed_distance_margin(A,B) <= break_distance`, then the `distance_lower_bound` contains `signed_distance_margin(A,B)`. The only thing which is left to be done is to retain the closest points.

Would we agree on this ?

2020-10-27 07:52 UTC, jcarpent commented
Yes, seems to be a very good solution.

2020-10-27 18:21 UTC, jmirabel commented
I close this in favor of #200

2020-10-27 18:21 UTC, closed without merging