Add CollisionResult::nearest_points
humanoid-path-planner/hpp-fcl pull request #200
Opened 2020-10-27 17:16 UTC by jmirabel

This supersedes #198 .

Work left to be done:
- [ ] agree on the API
- [ ] handle shape-shape collision
- [ ] add some unit test
- [ ] revise the distance lower bound (does not take the security margin).

Class ShapeCollisionTraversal should be removed.

As a bonus, this also solves #199.

2020-10-27 18:42 UTC, jmirabel commented
@nim65s does it make sense to turn off travis (except for osx) ?

2020-10-27 18:51 UTC, nim65s commented
I prefer not to have opinions about travis. If someone wants to use and maintain it, that's perfectly fine for me, but on my side I have enough work and results with one CI stack :)

2020-10-29 19:08 UTC, jmirabel commented
After some effort, I ended up with the following.
- for collision queries, all the returned distances take the security margin into account,
- the collision result stores valid nearest_points whenever the distance lower bound is inferior to `break_distance`. When the distance lower bound is higher, their validity depends upon the pair of object type (maybe we should add a boolean that says whether they are valid).
- the distance lower bound can be negative, in which case it is the opposite of the penetration depth (the security margin is taken into account).

This leads to one strange thing. With the current changes, when the distance lower bound is inferior to the break distance, we don't have `||AB|| = distance_lower_bound` but ||AB|| = distance_lower_bound + security_margin` (A and B being the nearest point). i.e. the nearest point are not on the shapes inflated by `security_margin/2`

Some improvements, kept for later:
- For BVH, the minimal distance between two bounding volumes could be decrease as the algo finds smaller distance lower bound. This is especially useful when the `break_distance` is set to a high value.
- Rename `break_distance` to something easier to understand from the user perspective.
- Clean API of CollisionTraversalNode:
  - remove ShapeCollisionTraversalNode,
  - merge the two CollisionTraversalNode::BVDisjoint prototype into one. The squared distance lower bound attribute is not useless.
- The above API should be enforced by some unit-tests.

2020-10-29 19:09 UTC, jmirabel commented
This PR is ready for reviews.

2020-11-04 17:12 UTC, jcarpent approved these changes

2020-11-04 17:12 UTC, jcarpent commented on src/collision.cpp
> +    it->normal *= -1;
This is a critical bug, isn't ?

2020-11-04 17:21 UTC, jmirabel commented on src/collision.cpp
> +    it->normal *= -1;
Yes. I am surprised it hasn't popup earlier.

2020-11-04 17:42 UTC, jmirabel commented on include/hpp/fcl/internal/traversal_node_bvh_shape.h
> +              -distance));
TODO: sometimes the contact distance takes the security margin into account. Sometimes it does not. It should be homogenized.

2020-11-04 18:21 UTC, jcarpent requested changes
Maybe, this should fix another bug

2020-11-04 18:21 UTC, jcarpent commented on src/collision_func_matrix.cpp
> +  if (distToCollision <= 0 && result.numContacts () < request.num_max_contacts) {
Currently, this results is not taking into account the break_distance information.
Compared to other collision checks.
```suggestion
  if (distToCollision <= request.break_distance && result.numContacts () < request.num_max_contacts) {
```

2020-11-05 08:06 UTC, jmirabel commented on src/collision_func_matrix.cpp
> +  if (distToCollision <= 0 && result.numContacts () < request.num_max_contacts) {
No, there is a contact only if distToCollision <= 0. At the moment, `break_distance` is not useful for shape-shape pairs.

2020-11-05 09:32 UTC, jcarpent commented on include/hpp/fcl/internal/traversal_node_bvh_shape.h
> +              -distance));
Why to not apply the change here?

2020-11-05 13:09 UTC, jmirabel commented on include/hpp/fcl/internal/traversal_node_bvh_shape.h
> +              -distance));
I plan to do it. I wrote it so as not to forget.

2022-02-08 13:10 UTC, jcarpent commented
@jmirabel Could you consider adjusting this PR for merging it?

2022-02-15 10:43 UTC, jmirabel commented
Not sure what you are asking exactly. I can definitely resolve the git conflicts quickly. Adding unit test, finalizing the code and maybe update the API is another story. I know I won't have time before beginning of March. Then I am not sure yet.

2022-02-15 10:52 UTC, jmirabel commented
I assigned myself so that I see this in my list of assigned PRs.

2022-05-24 14:34 UTC, jcarpent commented on src/collision_node.cpp
> -    result.updateDistanceLowerBound (sqrt (sqrDistLowerBound));
@jmirabel Why do you remove that here?

2022-06-04 08:09 UTC, jcarpent commented
Supersedes by #303.

2022-06-04 08:09 UTC, closed without merging