Add Octree bindings + some helpers
humanoid-path-planner/hpp-fcl pull request #206
Opened 2020-11-18 16:28 UTC by jcarpent

2020-11-18 16:34 UTC, jmirabel requested changes

2020-11-18 16:34 UTC, jmirabel commented on CMakeLists.txt
> +ENDIF(HPP_FCL_HAS_OCTOMAP)
This isn't backward compatible. I think we must keep the `HAVE` version for some time.

2020-11-18 16:34 UTC, jmirabel commented on include/hpp/fcl/fwd.hh
> +#ifdef HPP_FCL_HAS_COLLISION
Does this flag exists or is it a typo ?

2020-11-18 16:35 UTC, jmirabel commented on include/hpp/fcl/fwd.hh
> +#ifdef HPP_FCL_HAS_COLLISION
If you meant `HPP_FCL_HAS_OCTOMAP`, then, I think it isn't sufficient because code may use the preprocessor variable before including any hpp/fcl header.

2020-11-18 16:43 UTC, jcarpent commented on CMakeLists.txt
> +ENDIF(HPP_FCL_HAS_OCTOMAP)
```suggestion
"-DHPP_FCL_HAS_OCTOMAP -DHPP_FCL_HAVE_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=${OCTOMAP_MAJOR_VERSION} -DOCTOMAP_MINOR_VERSION=${OCTOMAP_MINOR_VERSION} -DOCTOMAP_PATCH_VERSION=${OCTOMAP_PATCH_VERSION}")
ENDIF(HPP_FCL_HAS_OCTOMAP)
```

2020-11-18 16:47 UTC, jcarpent commented on include/hpp/fcl/fwd.hh
> +#ifdef HPP_FCL_HAS_COLLISION
my bad. I will move it to the octree files.

2020-11-18 17:08 UTC, jmirabel commented on src/CMakeLists.txt
> +    -DHPP_FCL_HAS_OCTOMAP
```suggestion
    -DHPP_FCL_HAS_OCTOMAP
    -DHPP_FCL_HAVE_OCTOMAP
```
You need both here.

2020-11-18 17:08 UTC, jmirabel commented on include/hpp/fcl/octree.h
> +#define HPP_FCL_HAVE_COLLISION
```suggestion
```
I don't think `HPP_FCL_HAVE_COLLISION` ever existed. `HPP_FCL_HAVE_OCTOMAP` should go into the CMake.

2020-11-18 17:08 UTC, jmirabel commented on CMakeLists.txt
> +    "-DHPP_FCL_HAS_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=${OCTOMAP_MAJOR_VERSION} -DOCTOMAP_MINOR_VERSION=${OCTOMAP_MINOR_VERSION} -DOCTOMAP_PATCH_VERSION=${OCTOMAP_PATCH_VERSION}")
```suggestion
    "-DHPP_FCL_HAS_OCTOMAP -DHPP_FCL_HAVE_OCTOMAP -DFCL_HAVE_OCTOMAP -DOCTOMAP_MAJOR_VERSION=${OCTOMAP_MAJOR_VERSION} -DOCTOMAP_MINOR_VERSION=${OCTOMAP_MINOR_VERSION} -DOCTOMAP_PATCH_VERSION=${OCTOMAP_PATCH_VERSION}")
```
while here, we may delete the very old `FCL_HAVE_OCTOMAP`.

2020-11-18 17:08 UTC, jmirabel commented on CMakeLists.txt
> +ENDIF(HPP_FCL_HAS_OCTOMAP)
Your suggestion is good but seems to apply to the wrong line.

2020-11-19 07:21 UTC, jmirabel approved these changes
Thanks !

2020-11-21 10:00 UTC, jmirabel commented on python/math.cc
> +    if(i >= 3 || i <= -3)
isn't `-3` allowed ?

2021-03-02 14:57 UTC, merged