Fix constness + reduce Boost dependency.
humanoid-path-planner/hpp-fcl pull request #208
Opened 2021-01-20 11:12 UTC by jmirabel

2021-01-20 11:23 UTC, jcarpent requested changes
You are forcing the compilation against C++11, which is not something appealing at the current stage of the project, to just remove a minor dependency to Boost.

This is a bit too early I would say.

2021-01-20 11:23 UTC, jcarpent commented on include/hpp/fcl/profile.h
> +  Profiler(const Profiler&) = delete;
This is a C++11 feature!

2021-01-20 12:18 UTC, jmirabel commented on include/hpp/fcl/profile.h
> +  Profiler(const Profiler&) = delete;
You are correct. This was not my first intention. This file is anyway not used by anyone. I removed it.

2021-01-20 13:43 UTC, jmirabel commented
@jcarpent any idea why windows CI fails ?

2021-01-20 14:00 UTC, jcarpent commented
You should have a look to https://github.com/stack-of-tasks/pinocchio/commit/c0a3381de8681c4f38bde1a3dcd7894f300744e1#diff-290e375cf6344cd41694325176f37fab181cde59e19180067c1d37902af69b2c

2021-01-21 09:12 UTC, jmirabel commented
@jcarpent if it's okay, can you modify your review ? Now the code is C++98 compliant.

2021-01-21 09:20 UTC, jcarpent approved these changes

2021-01-21 09:56 UTC, merged