[WIP] Preparing for ROS1 and ROS2 release
humanoid-path-planner/hpp-fcl pull request #255
Opened 2022-01-26 14:22 UTC by wxmerkt

WIP - modifications to prepare for a release. Also addressing some warnings along the way and turning others off

2022-02-01 10:24 UTC, jcarpent commented on CMakeLists.txt
> +# TODO: These warnings should be fixed
Why do you want to remove that?
I think we need to tackle all the current warnings instead ...

2022-02-01 10:25 UTC, jcarpent commented on include/hpp/fcl/BVH/BVH_model.h
> +    // unsigned int other_num_primitives = 0;
Why did you comment here?

2022-02-01 10:25 UTC, jcarpent requested changes
Hi @wxmerkt !
I made some comments, could you handle them?
Best,
Justin

2022-02-01 10:33 UTC, wxmerkt commented on CMakeLists.txt
> +# TODO: These warnings should be fixed
They should, but there are hundreds. I turned these off to try to get the autodoc-ones resolved (Latex commands seen as escape characters; by changing the Python), but wasn't successful initially so stopped.

2022-02-01 10:34 UTC, wxmerkt commented on include/hpp/fcl/BVH/BVH_model.h
> +    // unsigned int other_num_primitives = 0;
It's set and not used -- the code below where it would be used is already commented

2022-02-08 13:14 UTC, jcarpent commented on CMakeLists.txt
> +# TODO: These warnings should be fixed
@wxmerkt Could you remove these lines?

2022-02-08 13:15 UTC, jcarpent commented on include/hpp/fcl/BVH/BVH_model.h
> +    // unsigned int other_num_primitives = 0;
Could you revert this change?

2022-02-08 19:06 UTC, wxmerkt commented on include/hpp/fcl/BVH/BVH_model.h
> +    // unsigned int other_num_primitives = 0;
If you take a look at the wider context of this function, the result of these lines is never used -- the lines that originally used them are commented below. Is there a reason to leave it in there if it's unused?

2022-02-09 08:57 UTC, jmirabel commented on include/hpp/fcl/BVH/BVH_model.h
> +    // unsigned int other_num_primitives = 0;
I agree it should have been commented in the first place.

2022-02-14 13:49 UTC, jcarpent approved these changes

2022-02-14 13:49 UTC, merged