Address some warnings
humanoid-path-planner/hpp-fcl pull request #262
Opened 2022-02-16 17:05 UTC by wxmerkt

Uses C++11 features which I expect will be default after #260 merges

Following this PR, the only warnings I see locally are from the Python-autodoc

2022-02-16 17:33 UTC, jcarpent approved these changes
Seems good to me.

2022-02-16 17:35 UTC, wxmerkt commented
Btw - before merging this, we need to merge https://github.com/jrl-umi3218/jrl-cmakemodules/pull/504 and then update cmake to the updated master

2022-02-16 21:13 UTC, wxmerkt commented
The "collision" test fails for me under clang both in master and in this branch. Is this a known issue? It appears fine using gcc

2022-02-16 21:15 UTC, jcarpent commented
It is Working well on my side with clang. Could you prepare a docker image for this issue?

2022-02-17 00:39 UTC, wxmerkt commented
This PR should be ready for a full review once CI comes back green.

The crash was due to it picking up an ABI incompatible copy of the library in another directory (likely an incorrect LD_LIBRARY_PATH at config time). Interestingly though, the error did not show with gcc. In either case, it's working in a Docker. Strangely enough though, the same error showed up in the Clang-ROS-CI-Config I just added (https://github.com/humanoid-path-planner/hpp-fcl/runs/5224552889?check_suite_focus=true#step:4:1755). It doesn't show if it's not sourced (which was required for Crocoddyl's CI setup); but that shouldn't mean much since it's a different build system anyways.

2022-02-18 09:38 UTC, jcarpent requested changes
@wxmerkt Thanks for this PR. Could you remove the reverted commits? They are not informative and seems to pollute the commit history.

2022-02-18 10:25 UTC, wxmerkt commented on src/broadphase/broadphase_dynamic_AABB_tree_array.cpp
> +  tree_topdown_balance_threshold = &dtree.bu_threshold;
dtree is used uninitialised - and adding a initialisation in the declaration doesn't address the issue since the int-ptr are declared before dtree is declared. By moving this line into the constructor, dtree is correctly initialised before the pointer is assigned

2022-02-21 07:28 UTC, jcarpent commented on src/narrowphase/gjk.cpp
> +    for(Vec3f::Index i = 0; i < 3; ++i)
int is fine here.

2022-02-21 07:28 UTC, jcarpent commented on src/narrowphase/gjk.cpp
> +      for(Vec3f::Index i = 0; i < 3; ++i)
Same here.

2022-02-21 07:29 UTC, jcarpent commented on src/narrowphase/gjk.cpp
> +    for(Vec3f::Index i = 0; i < 3; ++i)
`Index` is not supported by all Eigen version. One should rather rely on `DenseIndex`.

2022-02-21 07:30 UTC, wxmerkt commented on src/narrowphase/gjk.cpp
> +    for(Vec3f::Index i = 0; i < 3; ++i)
Indeed. I believe it was size_t when I started the branch and this is from resolving a rebase conflict. Should I revert? Is this a problem to change it to Vec3f::Index (which should resolve to the same)?

2022-02-21 07:38 UTC, jcarpent commented on src/narrowphase/gjk.cpp
> +    for(Vec3f::Index i = 0; i < 3; ++i)
The only thing with Index, it is that it has been introduced lately in Eigen. But I think it was in Eigen 3.3.0 if I remember well.

2022-02-21 08:16 UTC, wxmerkt commented on src/narrowphase/gjk.cpp
> +    for(Vec3f::Index i = 0; i < 3; ++i)
Do we have a supported configuration where Eigen is <3.3 (it has been released in Nov 2016)?

2022-02-21 09:20 UTC, jcarpent commented on src/narrowphase/gjk.cpp
> +    for(Vec3f::Index i = 0; i < 3; ++i)
I would say yes, if has no cost. I think @nim65s still have some CI with 16.04.

2022-02-21 09:43 UTC, wxmerkt commented on src/narrowphase/gjk.cpp
> +    for(Vec3f::Index i = 0; i < 3; ++i)
Ok, addressed

2022-02-21 09:57 UTC, jcarpent approved these changes
Thanks a lot @wxmerkt.

2022-02-21 10:20 UTC, jcarpent commented
After the CI is green, I will merge this PR.

2022-02-21 10:56 UTC, merged