Updated the cmake to be more configurable [WIP]
humanoid-path-planner/hpp-fcl pull request #350
Opened 2022-09-15 14:05 UTC by JeffHough

This PR is in response to issue #338.

I've added some options in the root `CMakeLists.txt` file, and set the default options so that things should be the same as they are now if no flags are set.

These are the new options:
```
OPTION(HPP_FCL_USE_OCTOMAP "Build hpp-fcl with octomap" ON)
OPTION(HPP_FCL_BUILD_TESTS "Build the tests or not" ON)
OPTION(HPP_FCL_BUILD_CORE_ONLY "Only build the core functionality of hpp-fcl (no mesh loaders, no ROS, no tests)" OFF)
OPTION(HPP_FCL_BUILD_SHARED_LIBRARY "Build hpp-fcl as a shared library. Otherwise static." ON)
```

All of the flags are pretty much what they sound like. 

For the `HPP_FCL_BUILD_CORE_ONLY`, this will not build anything related to catkin or colcon, and will also not include any mesh loaders (i.e. no longer requires `assimp`) and forces the tests to be off (the tests fail to link without assimp so cannot build). I added this flag for my own particular use case where I am embedding `hpp-fcl` in another application for collision-detection, and my mesh files are already loaded. That is, I do not need a mesh loader, and would prefer to not have the additional dependency.

2022-09-15 14:16 UTC, jcarpent requested changes
Thanks for this contribution. I made major comments which should be addressed.
In general, I think the way you implement your solution is very specific.

I don't think the introduction of `HPP_FCL_BUILD_CORE_ONLY` concept is really useful. This is not a clean solution. I made some suggestions to converge towards a better setup.
@nim65s Could you provide more feedback?

2022-09-15 14:16 UTC, jcarpent commented on CMakeLists.txt
> +OPTION(HPP_FCL_BUILD_TESTS "Build the tests or not" ON)
This is redundant with `BUILD_TESTING`. Could you remove it?

2022-09-15 14:16 UTC, jcarpent commented on CMakeLists.txt
> +  SET(HPP_FCL_BUILD_TYPE SHARED)
This should be rather named `HPP_FCL_LIBRARY_TYPE`

2022-09-15 14:16 UTC, jcarpent commented on CMakeLists.txt
> -FIND_PACKAGE(assimp REQUIRED)
We can make assimp as an optional dependency. Could you add it rather than using `HPP_FCL_BUILD_CORE_ONLY` which is a not a good practice.

2022-09-15 14:16 UTC, jcarpent commented on CMakeLists.txt
> +IF (HPP_FCL_BUILD_TESTS)
We should use BUILD_TESTING as default. Could you remove it?

2022-09-15 14:16 UTC, jcarpent commented on CMakeLists.txt
> +ENDIF()
You should not change that. This installation.

2022-09-15 14:16 UTC, jcarpent commented on CMakeLists.txt
> +ENDIF()
This setting is very specific to your own setting.
I prefer to make assimp optional, and to properly do it rather than trying to add specific build core which hard to maintain in the end

2022-09-15 15:26 UTC, JeffHough commented
@jcarpent thanks for all the feedback! 

As you're saying, this is basically a configuration that I found to work well for me, but I agree, the optional dependency of `assimp`, if wanted to be optional at all, could probably be done in a more general way.

When I have a bit of time I'll make the edits you recommend!

2022-09-16 07:13 UTC, nim65s reviewed
I agree with @jcarpent, and added a minor remark

2022-09-16 07:13 UTC, nim65s commented on CMakeLists.txt
> +OPTION(HPP_FCL_BUILD_SHARED_LIBRARY "Build hpp-fcl as a shared library. Otherwise static." ON)
I would be in favor of putting this option in the jrl-cmakemodules, to allow other projects to benefit from this.
But we can go ahead with this PR and merge it like this for now, if you are OK to rename this in a more general way later.

2022-10-12 14:19 UTC, closed without merging