update default C++ to 14
humanoid-path-planner/hpp-fcl pull request #410
Opened 2023-04-28 08:59 UTC by nim65s

to avoid hundreds of boost 1.81 warnings:
```
#warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
```

Also, there shouldn't be much use cases where C++11 is available and C++14 is not.

2023-04-28 10:09 UTC, jcarpent reviewed
It is a big jump

2023-04-28 18:34 UTC, jcarpent requested changes
Could we make it dependent on the Boost version to not force to much if it is not necessary?

2023-04-29 07:34 UTC, jcarpent commented
@wxmerkt It seems the ROS CI is failing (similarly to Pinocchio). Could you help us on it?

2023-04-29 08:54 UTC, nim65s commented on CMakeLists.txt
> +if(Boost_VERSION_STRING VERSION_LESS 1.82)
```suggestion
if(Boost_VERSION_STRING VERSION_LESS 1.81)
```

This would allow us to test it with Boost 1.81 and get rid of the warnings

2023-04-30 08:47 UTC, nim65s commented
I think we could merge this, and fix ROS-CI in another PR, especially because this other issues hits other repositories

2023-04-30 09:26 UTC, wxmerkt commented
The problems with ROS-CI were due to unavailability of the EigenPy binary on Rolling - this issue was temporary (RAM exhaustion) and has been resolved. I restarted the jobs so hopefully they should come back green now

2023-04-30 12:49 UTC, jcarpent approved these changes

2023-04-30 12:49 UTC, merged