Adding mesh double description
humanoid-path-planner/hpp-fcl pull request #450
Opened 2023-07-27 15:23 UTC by lmontaut

A polytope can be seen as either a set of vertices or a set of planes (normals + offsets).
The double description is normals + offsets.
In GJK/EPA we only use the vertices of polytopes. However, for computing normals/witness points, having the double description may be usefull in the future.

2023-07-27 15:46 UTC, lmontaut commented on src/shape/geometric_shapes.cpp
> +    nneighbors_ = nullptr;
For the moment the `ConvexBase/Convex<PolygonT>` always owns its `normals` and `offsets`.
However I can do the same strategy as for `points`.
For it to make sense though, this requires adding a constructor to `Convex<PolygonT>` or at least a function `buildDoubleRepresentation`.

2023-07-27 15:52 UTC, lmontaut commented on src/shape/geometric_shapes.cpp
> +    nneighbors_ = nullptr;
@jcarpent I can put a function `buildDoubleRepresentation` in `ConvexBase` and remove the normals construction from `ConvexBase::convexHull`.
Then, either the user calls `buildDoubleRepresentation` or we force the call to `buildDoubleRepresentation` at the end of `convexHull` (in the future, we might systematically need the double representation information for witness points after calling GJK/EPA).

2023-07-27 17:00 UTC, lmontaut commented
@jcarpent what do you think about changing `points`, `normals` and `offsets` in `ConvexBase` from a regular pointer to a `shared_ptr`? This would remove the concept of `own_storage` and simplify having to keep track whether a `Convex` owns its points representation and/or its normals + offsets representation.

2023-07-28 05:58 UTC, jcarpent commented on src/shape/geometric_shapes.cpp
> +    nneighbors_ = nullptr;
At first glance, the double description should not be computed when creating the objects to avoid any computational burden.

2023-07-28 06:38 UTC, lmontaut commented on src/shape/geometric_shapes.cpp
> +    nneighbors_ = nullptr;
Yes I agree but since we call Qhull inside `ConvexBase::convexHull`, we get the double representation for free. Calling it later would result in computationnal burden.
I will restructure the code so that `ConvexBase::convexHull` still constructs the double representation but `buildDoubleRepresentation` can still be called later i.e for `Convex` objects which have not been constructed by the `ConvexBase::convexHull` function.
Does this sound ok for you?

2023-07-28 09:18 UTC, jcarpent commented on src/shape/geometric_shapes.cpp
> +    nneighbors_ = nullptr;
Good to me.

2023-07-28 09:18 UTC, jcarpent commented on src/shape/geometric_shapes.cpp
> +    nneighbors_ = nullptr;
Maybe, adding a method hasDoubleDescription() could help by checking the content of the pointers (if they are not NULL for instance)

2023-07-28 09:22 UTC, jcarpent commented
> @jcarpent what do you think about changing `points`, `normals` and `offsets` in `ConvexBase` from a regular pointer to a `shared_ptr`? This would remove the concept of `own_storage` and simplify having to keep track whether a `Convex` owns its points representation and/or its normals + offsets representation.

Looks good to me. I do think we need to transition from raw pointers to smart ones in all the code.
A huge task, but will simplify our life in the very near future.

2023-08-10 10:22 UTC, jcarpent commented on include/hpp/fcl/shape/geometric_shapes.h
> +#endif
```suggestion
```

2023-08-10 10:22 UTC, jcarpent commented on include/hpp/fcl/shape/geometric_shapes.h
> +#endif
These includes are not needed.

2023-08-10 10:23 UTC, jcarpent commented on src/shape/convex.cpp
> -
You should keep them here.

2023-08-10 14:04 UTC, jcarpent commented on python/collision-geometries.cc
> +  typedef Eigen::Ref<RowMatrixX3> RefVecOfDoubles;
This is not totally correct. This is just a copy-pasting of previous lines.

2023-08-10 14:05 UTC, jcarpent commented on python/collision-geometries.cc
> +      VecOfDoubles;
I would call it VectorX.

2023-08-10 14:05 UTC, jcarpent requested changes

2023-08-10 14:05 UTC, jcarpent commented on python/collision-geometries.cc
> +      VecOfDoubles;
Row::Major is not needed. You can also use Eigen::VectorXd

2023-09-22 13:45 UTC, merged