Setting default parameters for the narrowphase
humanoid-path-planner/hpp-fcl pull request #531
Opened 2024-02-08 15:46 UTC by lmontaut

This PR is related to #380 where users are sometimes experiencing assertion errors in Debug mode.
This PR is related to one of these assertion triggers:
- When the user sets a tolerance for GJK and/or EPA that is too low, the support function may work with support directions that are almost zero, which is not suitable for GJK and EPA. In hppfcl, we have hard-coded assertion checks, and these checks make the assumption that GJK's tolerance is not below `1e-6`. This PR introduces default values for GJK and EPA and places a warning in Debug mode only for users going below this tolerance.
Side note: when working with the default GJK and EPA (default `1e-6` tolerance, default convergence criterion), it is precise up to the micro-meter, which is an **extremely** low tolerance. In practice, working with `1e-4` or even 1e-3` should be more than enough.

Sorry for the long coming text.
I will use this PR to evoke the 2 main other assertions that sometimes trigger:
- When shapes of a collision pair are extremely far apart or have extremely different dimensions (i.e., a molecule vs. a plane), the projection step in GJK may be limited due to floating point error, and assertions will be triggered. We might want to implement a "pre-conditioning" system in the future. When working with "molecule vs. plane" dimensions, it would warn the user that hppfcl is not made to work with such different dimensions. When working with "molecule vs. molecule" dimensions, it would simply scale the problem "to the meter." This pre-conditioner would simply check the dimension of the AABB of each shape.
- When shapes of a collision pair are in "touching contact", i.e they are colliding but have a 0 penetration depth. In such a case, EPA tries to run, fails, and an assert triggers. Although this situation in "rare" in theory, it actually occurs quite often when using hppfcl for physics simulation. I am actively working on fixing this issue, so hopefully this assert will soon disappear.

2024-02-08 19:10 UTC, lmontaut commented
This PR also fixes additional assertion errors in GJK and BVH thanks to tests provided by #382

2024-02-08 19:59 UTC, jcarpent approved these changes

2024-02-08 20:01 UTC, jcarpent commented on test/collision_node_asserts.cpp
> +
```suggestion

#define _USE_MATH_DEFINES
```

2024-02-08 20:02 UTC, jcarpent approved these changes

2024-02-09 09:27 UTC, jorisv requested changes

2024-02-09 09:27 UTC, jorisv commented on include/hpp/fcl/narrowphase/narrowphase_defaults.h
> +#define EPA_DEFAULT_MAX_VERTICES 64
Instead of define, use global constant and put in a namespace.

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es31-dont-use-macros-for-constants-or-functions

2024-02-09 09:27 UTC, jorisv commented on src/collision_node.cpp
> +               dummy_precision);
This code is checking if the result is correct.

1. Are you sure throwing an exception is not a better behavior ?
2. I would put this code in a separated static function (for the symbol visibility) to split the useful code from the error checking.

2024-02-09 09:27 UTC, jorisv commented on src/narrowphase/gjk.cpp
> +      100 * std::numeric_limits<FCL_REAL>::epsilon());
I think you can remove the static keyword here.

2024-02-09 09:27 UTC, jorisv commented on test/collision_node_asserts.cpp
> +#include <cmath>
Instead of using _USE_MATH_DEFINES you can use `boost::math::constants::pi<Real>()` from `#include <boost/math/constants/constants.hpp>`

2024-02-09 09:27 UTC, jorisv commented on test/gjk_asserts.cpp
> +#include <cmath>
Same than previous issue

2024-02-09 09:27 UTC, jorisv commented on test/collision_node_asserts.cpp
> +inline double DegToRad(const double& deg) {
```suggestion
double DegToRad(const double& deg) {
```

2024-02-09 09:27 UTC, jorisv commented on test/gjk_asserts.cpp
> +inline double DegToRad(const double& deg) {
```suggestion
double DegToRad(const double& deg) {
```

2024-02-09 09:27 UTC, jorisv commented on test/gjk_asserts.cpp
> +inline void CreateSphereMesh(BVHModel<OBBRSS>& model, const double& radius) {
```suggestion
void CreateSphereMesh(BVHModel<OBBRSS>& model, const double& radius) {
```

2024-02-09 09:27 UTC, jorisv commented on test/gjk_asserts.cpp
> +  const float PI = static_cast<float>(M_PI);
boost::math::constants::pi

2024-02-09 09:27 UTC, jorisv commented on test/gjk_asserts.cpp
> +  }
I don't get the purpose of this test. It test if the assertion in collision_node are not trigger ?

I find it weird to test an assertion (the test is only valid in DEBUG mode). Also, I would test that te assertion IS thrown and not that there is no assertion (you don't validate the error case).

2024-02-09 10:12 UTC, lmontaut commented on test/gjk_asserts.cpp
> +  }
I agree with you @jorisv. The thing is: without this test, I would not have been able to debug the assertion in GJK. Now that the assertion is fixed, this test is basically useless and will always pass...
Also, we can't really design a test that **does** trigger the GJK assertion because the point is that we **don't** want the GJK assertion to trigger.

What do you think is good practice? Should we remove this test?

2024-02-09 10:18 UTC, lmontaut commented on src/collision_node.cpp
> +               dummy_precision);
I think you're right, this should probably throw an exception.

Contrary to the assertions in GJK for which GJK has a fallback behavior and will still work fine, here if the asserts are triggered it means the entire collide call is wrong.
So throwing an exception is probably better.

2024-02-09 10:51 UTC, lmontaut commented on src/collision_node.cpp
> +               dummy_precision);
Got update from @jcarpent.
This is deep in the code and the throw will slow things down. I will keep the function but replace the throws by asserts.

2024-02-09 14:59 UTC, jorisv approved these changes

2024-02-09 16:47 UTC, merged