Renamming the library to `Coal`
humanoid-path-planner/hpp-fcl pull request #596
Opened 2024-06-24 10:01 UTC by lmontaut

This PR addresses #593 and aims at changing the name of the library from `hpp-fcl` to `coal`.

For the end-user, this renaming implies the following changes:
- In CMake: `find_package(hpp-fcl)` -> `find_package(coal)`.
- In C++: `#include <hpp/fcl/...>` -> `#include <coal/...>`.
- In Python: `import hppfcl` -> `import coal`.

I have added a layer of compatibility such that the namespace `hpp::fcl::` is still available and points to `coal::`.
However, all users are encouraged to use `coal::` instead of `hpp::fcl::`.

I also took the opportunity to change and clarify certain fundamental types used throughout the library:
- `FCL_REAL` -> `CoalScalar`.
- `Matrix/Vec[...]f` (i.e. `Vec3f`) -> `Matrix/Vec[...]s` (i.e. `Vec3s`).
- `Transform3f` -> `Transform3s`.
The idea behind this change is that multiple people have reported that they found the `f` at the end of these types confusing because they thought it referred to `float` when the library is `double` by default.
Like the namespace, I kept the old data types, but all users are encouraged to switch to the new ones.

Things left to do:
- [ ] package.xml
- [ ] update readme
- [ ] github workflow
- [ ] github repo name
- [ ] paths to be changed in Python unit tests (`octree`, `distance_lower_bound`, and `collision`)
- [ ] conda build

2024-06-25 06:00 UTC, jcarpent commented
Should wait for #598 to be merged.

2024-06-25 14:55 UTC, wxmerkt commented
For ROS, we may need to make a set of fresh releases to avoid breaking existing packages (and it'll take some time to get dialed in during which any updated downstream projects may fail). Ping me when it's merged and I can get started on the weekend(s)

2024-06-26 15:25 UTC, wxmerkt commented
@jcarpent One more thought - would you be open to us first fixing all the warnings before renaming so we can stop the email flood for "unstable" builds for the then no-longer-releasable hpp-fcl library?

2024-06-27 07:23 UTC, jcarpent commented
> @jcarpent One more thought - would you be open to us first fixing all the warnings before renaming so we can stop the email flood for "unstable" builds for the then no-longer-releasable hpp-fcl library?

Yes, sure. @lmontaut will integrate your change into the renamed lib.
Thanks a lot @wxmerkt for your nice contributions.

2024-06-28 07:51 UTC, nim65s commented
> * In CMake: `find_package(hpp-fcl)` -> `find_package(coal)`.
> * In C++: `#include <hpp/fcl/...>` -> `#include <coal/...>`.
> * In Python: `import hppfcl` -> `import coal`.

Those alone can require quite significant work. I would be in favor of providing an hpp-fcl CMake package, hpp/fcl include dir, and hppfcl python module which would raise some warning when used, but then redirect / symlink / alias to coal.

I think we should be able to least configure/build/test pinocchio in its current form without requiring any change.

2024-07-03 14:32 UTC, jorisv commented
Hello @nim65s,

I agree that providing a full CMake/Python/C++ compatibility is a nice option.

I also think this option should not be activated in coal package (conda, nix, apt, ...). Since coal don't have the same name than hpp-fcl, we will be allowed by many packaging system to install coal and hpp-fcl at the same time. In this case, the compatibility files will conflict with the hpp-fcl files and create some hard to debug issues.

One option can be to release a hpp-fcl v3 package that depend of coal and provide the compatibility files.
Another option is to forbid the installation of hpp-fcl and coal in the same time, but I don't know if all package manager provide this option.

2024-07-03 21:05 UTC, nim65s commented
Yes, from a package manager point of view, coal should replace hpp-fcl. In archlinux terms, this is `conflicts=('hpp-fcl')` + `provides=('hpp-fcl')`. In python terms, this is `Obsoletes-Dist: hpp-fcl` for coal, and `Provides-Dist: coal` for hpp-fcl.
For monorepo package managers like robotpkg or nix, we don't care.

> One option can be to release a hpp-fcl v3 package that depend of coal and provide the compatibility files.

I already implemented that, and I'm testing this solution in various scenarii.

2024-07-11 12:14 UTC, nim65s commented
ref. https://github.com/lmontaut/hpp-fcl/pull/1

2024-07-22 15:24 UTC, jorisv approved these changes

2024-07-24 22:47 UTC, nim65s commented
I'd prefer  if we could decouple the workspace change from the rename change. This PR is already impossible to review.

2024-07-24 22:48 UTC, nim65s commented on src/CMakeLists.txt
> +add_library(hpp-fcl::hpp-fcl ALIAS ${LIBRARY_NAME})
I would expect this to break with COAL_BACKWARD_COMPATIBILITY_WITH_HPP_FCL, because we can't define twice the same target

2024-07-24 22:49 UTC, nim65s commented on python/CMakeLists.txt
> +<<<<<<< HEAD
this probably should not be in git history

2024-07-24 22:51 UTC, nim65s commented on CMakeLists.txt
> +  FINDPYTHON(REQUIRED)
What is the goal of this ?
This is already done once in eigenpy. Doing it again would allow finding another interpreter, and breaking everything.

2024-07-24 22:53 UTC, nim65s commented on src/CMakeLists.txt
> +endif()
this is already done in hpp-fclTargets.cmake

2024-07-25 08:14 UTC, nim65s requested changes
Some more extensive tests show that a couple fixes are required. I pushed those on https://github.com/lmontaut/hpp-fcl/pull/4.

2024-07-25 08:18 UTC, lmontaut commented
> I'd prefer if we could decouple the workspace change from the rename change. This PR is already impossible to review.

Yes it's my bad, sorry. I should have waited for this PR to be merged to merge @jorisv's changes. @nim65s I can revert the changes if you want.

2024-07-25 19:28 UTC, jorisv commented on CMakeLists.txt
> +  FINDPYTHON(REQUIRED)
Python is a direct dependency of our project. Taking a direct dependency transitively is not a good behavior in my point of view.
Also, FINDPYTHON set the guard  `FINDPYTHON_ALREADY_CALLED` that will avoid running findpython again in eigenpy.

2024-07-25 19:32 UTC, jorisv commented on src/CMakeLists.txt
> +endif()
It's mandatory because of the workspace feature. Our project must setup the same targets than the hpp-fcl module. This allow also to use our project via find_package or add_subdirectory without modifying consumer.

2024-07-25 19:41 UTC, jorisv commented on src/CMakeLists.txt
> +add_library(hpp-fcl::hpp-fcl ALIAS ${LIBRARY_NAME})
I don't get in what commit do you find this line.
In the final merge, the alias is only setup if COAL_BACKWARD_COMPATIBILITY_WITH_HPP_FCL is set.

2024-07-25 19:43 UTC, jorisv commented on python/CMakeLists.txt
> +<<<<<<< HEAD
I'm pretty sure not all commit from this PR will create a stable/buildable project. So do we really care ?

2024-07-26 10:06 UTC, nim65s commented on src/CMakeLists.txt
> +endif()
Ok, now I understand, thanks. This code path would not be interpreted in the same use cases as hpp-fclTargets.cmake.

2024-07-26 10:08 UTC, nim65s commented
We should probably push the topic/coal branch to this repo, to have easier ways of making PR to that branch. I had to make some to your fork instead, which make the history harder to follow. I think this is fine for now, we can avoid the extra cost of undoing and re-doing again. But next time, I really think we need to use a cleaner workflow

2024-11-20 12:55 UTC, merged